import { supabase } from './supabase.js';

const PROFILE_FIELDS='id,name,username,avatar_url,bio,created_at';
const err=(e,f)=>e?.message?`${f}: ${e.message}`:f;
const clean=u=>String(u||'pixorauser').replace(/^@/,'').toLowerCase().replace(/[^a-z0-9._]/g,'').slice(0,30)||'pixorauser';

export async function currentUser(){const {data,error}=await supabase.auth.getUser();if(error)throw error;return data.user;}
export async function ensureProfile(user){if(!user)return null;const m=user.user_metadata||{};let {data,error}=await supabase.from('profiles').select(PROFILE_FIELDS).eq('id',user.id).maybeSingle();if(error)throw new Error(err(error,'Could not load your Pixora profile'));if(data)return data;let base=clean(m.username||m.name||user.email?.split('@')[0]);let username=base;for(let i=0;i<50;i++){let q=await supabase.from('profiles').select('id').eq('username',username).maybeSingle();if(q.error)throw new Error(err(q.error,'Could not check username'));if(!q.data)break;username=clean(`${base.slice(0,24)}_${Math.floor(1000+Math.random()*9000)}`)}let p={id:user.id,name:m.name||m.full_name||user.email?.split('@')[0]||'Pixora User',username,bio:m.bio||'',avatar_url:m.avatar_url||m.avatar||''};let r=await supabase.from('profiles').upsert(p,{onConflict:'id'}).select(PROFILE_FIELDS).single();if(r.error)throw new Error(err(r.error,'Could not create your Pixora profile'));return r.data;}
export async function myProfile(){return ensureProfile(await currentUser())}
export async function getProfileByUsername(username){let {data,error}=await supabase.from('profiles').select(PROFILE_FIELDS).eq('username',clean(username)).maybeSingle();if(error)throw new Error(err(error,'Could not load this Pixora profile'));return data;}
export async function searchProfiles(q=''){let query=supabase.from('profiles').select(PROFILE_FIELDS).order('name').limit(50);let v=String(q||'').trim().replace(/[%(),]/g,'');if(v)query=query.or(`name.ilike.%${v}%,username.ilike.%${v}%`);let {data,error}=await query;if(error)throw new Error(err(error,'Could not search Pixora users'));return data||[];}
export async function updateProfile(v){let u=await currentUser();if(!u)throw new Error('Please log in first.');let r=await supabase.from('profiles').update({name:String(v.name||'Pixora User').trim()||'Pixora User',username:clean(v.username),bio:String(v.bio||'').trim(),avatar_url:v.avatar_url||''}).eq('id',u.id).select(PROFILE_FIELDS).single();if(r.error)throw new Error(err(r.error,'Could not update your Pixora profile'));return r.data;}
export async function uploadImage(file,folder='posts'){let u=await currentUser();if(!u)throw new Error('Please log in first.');if(!file)throw new Error('Choose an image first.');let ext=(file.name?.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'')||'jpg';let path=`${u.id}/${folder}/${crypto.randomUUID()}.${ext}`;let {error}=await supabase.storage.from('posts').upload(path,file,{upsert:false,contentType:file.type||'image/jpeg'});if(error)throw new Error(err(error,'Image upload failed'));return supabase.storage.from('posts').getPublicUrl(path).data.publicUrl;}
async function profiles(ids){let a=[...new Set((ids||[]).filter(Boolean))];if(!a.length)return new Map();let {data,error}=await supabase.from('profiles').select(PROFILE_FIELDS).in('id',a);if(error)throw new Error(err(error,'Could not load Pixora profiles'));return new Map((data||[]).map(p=>[p.id,p]));}
export async function listPosts(){let {data,error}=await supabase.from('posts').select('id,author_id,content,image_url,created_at').order('created_at',{ascending:false}).limit(100);if(error)throw new Error(err(error,'Could not load Pixora posts'));let ps=await profiles((data||[]).map(x=>x.author_id));return (data||[]).map(x=>({...x,profiles:ps.get(x.author_id)||null}));}
export async function createPost({content,imageUrl}){let u=await currentUser();if(!u)throw new Error('Please log in first.');let {data,error}=await supabase.from('posts').insert({author_id:u.id,content:content||'',image_url:imageUrl||null}).select('id,author_id,content,image_url,created_at').single();if(error)throw new Error(err(error,'Could not publish post'));return data;}
export async function isFollowing(id){let u=await currentUser();let {data,error}=await supabase.from('follows').select('id').eq('follower_id',u.id).eq('following_id',id).maybeSingle();if(error)throw error;return !!data;}
export async function toggleFollow(id){let u=await currentUser();if(!u)throw new Error('Please log in first.');if(u.id===id)return false;let {data,error}=await supabase.from('follows').select('id').eq('follower_id',u.id).eq('following_id',id).maybeSingle();if(error)throw error;if(data){let r=await supabase.from('follows').delete().eq('follower_id',u.id).eq('following_id',id);if(r.error)throw r.error;return false;}let r=await supabase.from('follows').insert({follower_id:u.id,following_id:id});if(r.error)throw r.error;return true;}
export async function getCounts(id){let [a,b,c]=await Promise.all([supabase.from('follows').select('*',{count:'exact',head:true}).eq('following_id',id),supabase.from('follows').select('*',{count:'exact',head:true}).eq('follower_id',id),supabase.from('posts').select('*',{count:'exact',head:true}).eq('author_id',id)]);if(a.error)throw a.error;if(b.error)throw b.error;if(c.error)throw c.error;return {followers:a.count||0,following:b.count||0,posts:c.count||0};}
async function findConversation(other){let me=await currentUser();let {data,error}=await supabase.from('conversation_members').select('conversation_id').eq('user_id',me.id);if(error)throw new Error(err(error,'Could not load conversations'));let ids=(data||[]).map(x=>x.conversation_id);if(!ids.length)return null;let q=await supabase.from('conversation_members').select('conversation_id').eq('user_id',other).in('conversation_id',ids);if(q.error)throw new Error(err(q.error,'Could not find this conversation'));return q.data?.[0]?.conversation_id||null;}
async function createConversation(other){let me=await currentUser();let {data,error}=await supabase.from('conversations').insert({}).select('id').single();if(error)throw new Error(err(error,'Could not create conversation'));let r=await supabase.from('conversation_members').insert([{conversation_id:data.id,user_id:me.id},{conversation_id:data.id,user_id:other}]);if(r.error)throw new Error(err(r.error,'Could not add conversation members'));return data.id;}
async function conversation(other){return (await findConversation(other))||await createConversation(other);}
export async function listMessages(other){let id=await findConversation(other);if(!id)return [];let {data,error}=await supabase.from('messages').select('id,conversation_id,sender_id,content,created_at,read_at').eq('conversation_id',id).order('created_at',{ascending:true});if(error)throw new Error(err(error,'Could not load this conversation'));return data||[];}
export async function sendMessage(recipientId,body){let me=await currentUser();if(!me)throw new Error('Please log in first.');let text=String(body||'').trim();if(!recipientId)throw new Error('Recipient not found.');if(me.id===recipientId)throw new Error('You cannot message yourself.');if(!text)return null;let {data:recipient,error:re}=await supabase.from('profiles').select('id').eq('id',recipientId).maybeSingle();if(re)throw re;if(!recipient)throw new Error('User not found.');let cid=await conversation(recipientId);let {data,error}=await supabase.from('messages').insert({conversation_id:cid,sender_id:me.id,content:text}).select('id,conversation_id,sender_id,content,created_at,read_at').single();if(error)throw new Error(err(error,'Message could not be sent'));return data;}
export async function listNotifications(){let me=await currentUser();let {data,error}=await supabase.from('notifications').select('id,user_id,actor_id,type,title,message,post_id,conversation_id,is_read,created_at').eq('user_id',me.id).order('created_at',{ascending:false}).limit(100);if(error)throw new Error(err(error,'Could not load notifications'));let ps=await profiles((data||[]).map(x=>x.actor_id));return (data||[]).map(x=>({...x,actor:ps.get(x.actor_id)||null}));}
export async function markNotificationsRead(){let me=await currentUser();let {error}=await supabase.from('notifications').update({is_read:true}).eq('user_id',me.id).eq('is_read',false);if(error)throw error;}
export async function unreadCounts(){let me=await currentUser();let {count,error}=await supabase.from('notifications').select('*',{count:'exact',head:true}).eq('user_id',me.id).eq('is_read',false);if(error)throw error;return {notifications:count||0,messages:0};}
